### ISSUE TITLE
Why is the performance in this repo much better than paper?

### ISSUE THREAD

**Issue by ThisisBillhe** [WeixiangXu/STTN#1]
any tricks or reasons?

**Comment by Cyber-Neuron** [comment]
The avgpool and preBN are two of the tricks.

**Comment by Cyber-Neuron** [comment]
> any tricks or reasons?

I think the avgpool, trining epochs, and preBN are some of the tricks.

**Comment by WeixiangXu** [comment]
sorry for late reply, the link may help.
https://github.com/HolmesShuan/Training-Tricks-for-Binarized-Neural-Networks
